# Base configs
- type: dungeonConfig
  id: PlanetBase
  abstract: true
  layers:
  - !type:PrefabDunGen
    presets:
    - Bucket
    - Wow
    - SpaceShip
    - Tall

  - !type:CorridorPostGen
    width: 3

  - !type:DungeonEntrancePostGen
    count: 2

  - !type:RoomEntrancePostGen

  - !type:EntranceFlankPostGen

  - !type:ExternalWindowPostGen

  - !type:WallMountPostGen

  - !type:BoundaryWallPostGen

  - !type:JunctionPostGen
    width: 1

  - !type:JunctionPostGen

  - !type:AutoCablingPostGen

  - !type:CornerClutterPostGen

  - !type:CorridorDecalSkirtingPostGen
    cardinalDecals:
      South: BrickTileWhiteLineS
      East: BrickTileWhiteLineE
      North: BrickTileWhiteLineN
      West: BrickTileWhiteLineW
    cornerDecals:
      SouthEast: BrickTileWhiteCornerSe
      SouthWest: BrickTileWhiteCornerSw
      NorthEast: BrickTileWhiteCornerNe
      NorthWest: BrickTileWhiteCornerNw
    pocketDecals:
      SouthWest: BrickTileWhiteInnerSw
      SouthEast: BrickTileWhiteInnerSe
      NorthWest: BrickTileWhiteInnerNw
      NorthEast: BrickTileWhiteInnerNe

# Setups
- type: dungeonConfig
  id: Experiment
  data:
    colors:
      Decals: "#D381C996"
    entities:
      Cabling: CableApcExtension
      CornerWalls: WallReinforced
      Junction: BaseAirlock
      Walls: WallSolid
    spawnGroups:
      CornerClutter: BaseClutter
      Entrance: BaseAirlock
      EntranceFlank: BaseWindow
      WallMounts: ScienceLabsWalls
      Window: BaseWindow
    tiles:
      FallbackTile: FloorSteel
    whitelists:
      Rooms:
        tags:
        - SalvageExperiment
  layers:
  - !type:PrototypeDunGen
    proto: PlanetBase

- type: dungeonConfig
  id: Haunted
  data:
    entities:
      Wall: WallRock
    tiles:
      FallbackTile: FloorCaveDrought
    whitelist:
      Rooms:
        tags:
        - Mineshaft
  layers:
  - !type:PrefabDunGen
    presets:
    - Bucket
    - Wow
    - SpaceShip
    - Tall

  - !type:WormCorridorPostGen
    width: 3

  - !type:CorridorClutterPostGen
    contents:
    - id: FloraStalagmite1
    - id: FloraStalagmite2
    - id: FloraStalagmite3
    - id: FloraStalagmite4
    - id: FloraStalagmite5
    - id: FloraStalagmite6

  - !type:BoundaryWallPostGen

- type: dungeonConfig
  id: LavaBrig
  data:
    colors:
      Decals: "#DE3A3A96"
    entities:
      Cabling: CableApcExtension
      CornerWalls: WallReinforced
      Junction: BaseAirlock
      Walls: WallSolid
    spawnGroups:
      CornerClutter: BaseClutter
      Entrance: LavaBrigEntrance
      EntranceFlank: BaseWindow
      WallMounts: ScienceLabsWalls
      Window: BaseWindow
    whitelists:
      Rooms:
        tags:
        - LavaBrig
  layers:
  - !type:PrototypeDunGen
    proto: PlanetBase

- type: dungeonConfig
  id: Mineshaft
  data:
    entities:
      Cabling: Catwalk
    spawnGroups:
      CornerClutter: MineshaftClutter
      Entrance: BaseWoodWall
      EntranceFlank: BaseWoodWall
      Junction: RandomWoodenSupport
      Window: BaseWoodWall
    tiles:
      FallbackTile: FloorCaveDrought
    whitelist:
      Rooms:
        tags:
        - Mineshaft
  layers:
  - !type:PrototypeDunGen
    proto: PlanetBase

- type: dungeonConfig
  id: SnowyLabs
  data:
    colors:
      Decals: "#4cc7aa96"
    entities:
      Cabling: CableApcExtension
      CornerClutter: BaseClutter
      CornerWalls: WallSilver
      Junction: BaseAirlock
      Walls: WallSilver
    spawnGroups:
      Entrance: SnowyLabsEntrance
      EntranceFlank: BaseWindow
      WallMounts: SnowyLabsWalls
      Window: BaseWindow
    tiles:
      FallbackTile: FloorSteel
    whitelists:
      Rooms:
        tags:
        - SnowyLabs
  layers:
  - !type:PrototypeDunGen
    proto: PlanetBase

# Spawn groups
# Basic
- type: entitySpawnEntry
  id: BaseClutter
  entries:
  - id: PottedPlantRandom
    amount: 1

- type: entitySpawnEntry
  id: BaseAirlock
  entries:
  - id: CableApcExtension
  - id: AirlockGlass

- type: entitySpawnEntry
  id: BaseWindow
  entries:
  - id: Grille
  - id: Window

# Lava brig
- type: entitySpawnEntry
  id: LavaBrigEntrance
  entries:
  - id: CableApcExtension
  - id: AirlockSecurityGlassLocked

# Mineshaft
- type: entitySpawnEntry
  id: BaseWoodWall
  entries:
  - id: RandomWoodenWall

- type: entitySpawnEntry
  id: BaseWoodSupport
  entries:
  - id: RandomWoodenSupport

- type: entitySpawnEntry
  id: MineshaftClutter
  entries:
  - id: RandomStalagmiteOrCrystal
    amount: 1

- type: entitySpawnEntry
  id: MineshaftWalls
  entries:
  # Ore
  - id: WallRockSalt
    prob: 0.6
    orGroup: content
  - id: WallRockCoal
    prob: 0.6
    orGroup: content
  - id: WallRockTin
    prob: 0.4
    orGroup: content
  - id: WallMining
    prob: 0.8
    orGroup: content

# Science lab
- type: entitySpawnEntry
  id: ScienceLabsWalls
  entries:
  # Posters
  - id: RandomPosterLegit
    orGroup: content
  - id: ExtinguisherCabinetFilled
    prob: 0.2
    orGroup: content
  - id: RandomPainting
    prob: 0.05
    orGroup: content
  - id: IntercomCommon
    prob: 0.1
    orGroup: content

# Snowy labs
- type: entitySpawnEntry
  id: SnowyLabsEntrance
  entries:
  - id: CableApcExtension
  - id: AirlockFreezerHydroponicsLocked

- type: entitySpawnEntry
  id: SnowyLabsWalls
  entries:
  # Posters
  - id: RandomPosterLegit
    orGroup: content
  - id: ExtinguisherCabinetFilled
    prob: 0.2
    orGroup: content
  - id: RandomPainting
    prob: 0.05
    orGroup: content
  - id: IntercomScience
    prob: 0.1
    orGroup: content
