#Misc outfit startingGear definitions.

#Skeleton Biker - Just a skeleton now
- type: startingGear
  id: SkeletonBiker
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorBlack
    back: ClothingBackpack
    head: ClothingHeadBandSkull
    eyes: ClothingEyesGlassesSunglasses
    outerClothing: ClothingOuterCoatGentle
    gloves: ClothingHandsGlovesFingerless
    shoes: ClothingShoesBootsJack
    id: PassengerPDA
    ears: ClothingHeadsetGrey
  storage:
    back:
    - BoxSurvival

#Deathsquad Outfit
- type: startingGear
  id: DeathSquadGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitDeathSquad
    back: ClothingBackpackDeathSquad
    mask: ClothingMaskGasDeathSquad
    eyes: ClothingEyesHudSecurity
    ears: ClothingHeadsetAltCentCom
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitDeathsquad
    suitstorage: AirTankFilled
    shoes: ClothingShoesBootsMagAdv
    id: DeathsquadPDA
    pocket1: EnergySword
    pocket2: EnergyShield
    belt: ClothingBeltMilitaryWebbingMedFilled
  storage:
    back:
    - BoxSurvivalEngineering
    - WeaponPulseRifle
    - WeaponPulsePistol
    - WeaponRevolverMateba
    - SpeedLoaderMagnumAP
    - SpeedLoaderMagnumAP
    - BoxFlashbang
    - ToolDebug # spanish army knife
    - WelderExperimental
    - Hypospray
    - DeathAcidifierImplanter # crew will try to steal their amazing hardsuits
    - FreedomImplanter

# Syndicate Footsoldier Gear
- type: startingGear
  id: SyndicateFootsoldierGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitOperative
    head: ClothingHeadHelmetSwatSyndicate
    mask: ClothingMaskGas
    outerClothing: ClothingOuterArmorBasic
    ears: ClothingHeadsetAltSyndicate
    gloves: ClothingHandsGlovesCombat
    back: ClothingBackpack
    shoes: ClothingShoesBootsCombat
    id: SyndiPDA
  storage:
    back:
    - BoxSurvival

# Syndicate Footsoldier Gear - No Headset
- type: startingGear
  id: SyndicateFootsoldierGearRuin
  equipment:
    jumpsuit: ClothingUniformJumpsuitOperative
    head: ClothingHeadHelmetSwatSyndicate
    mask: ClothingMaskGas
    outerClothing: ClothingOuterArmorBasic
    gloves: ClothingHandsGlovesCombat
    back: ClothingBackpack
    shoes: ClothingShoesBootsCombat
    id: SyndiPDA
  storage:
    back:
    - BoxSurvival

# Nanotrasen Paramilitary Unit Gear
- type: startingGear
  id: NanotrasenParamilitaryGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSec
    back: ClothingBackpackSecurity
    shoes: ClothingShoesBootsCombatFilled
    eyes: ClothingEyesGlassesSecurity
    head: ClothingHeadHelmetSwat
    mask: ClothingMaskGasSwat
    outerClothing: ClothingOuterArmorBasicSlim
    ears: ClothingHeadsetSecurity
    gloves: ClothingHandsGlovesCombat
  storage:
    back:
    - BoxSurvivalSecurity
    - Flash
    - MagazinePistol

#CBURN Unit Gear - Full Kit
- type: startingGear
  id: CBURNGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorBrown
    back: ClothingBackpackDuffelCBURN
    mask: ClothingMaskGasERT
    eyes: ClothingEyesGlassesSecurity
    ears: ClothingHeadsetAltCentCom
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitCBURN
    shoes: ClothingShoesBootsCombatFilled
    id: CBURNPDA
    pocket1: RadioHandheld
    pocket2: WeaponLaserGun
    suitstorage: OxygenTankFilled
    belt: ClothingBeltBandolier
  storage:
    back:
    - BoxSurvivalEngineering
    - WeaponShotgunDoubleBarreled
    - BoxShotgunIncendiary
    - GrenadeFlashBang
    - PillAmbuzolPlus
    - PillAmbuzol

- type: startingGear
  id: BoxingKangarooGear
  equipment:
    gloves: ClothingHandsGlovesBoxingBlue

- type: startingGear
  id: MobMonkeyGear
  equipment:
    head: ClothingHeadHatTophat
    ears: ClothingHeadsetService
    jumpsuit: ClothingUniformJumpsuitJacketMonkey
    id: PunPunIDCard

# DeathMatch Gear

- type: startingGear
  id: DeathMatchGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorWhite
    shoes: ClothingShoesBootsJack
    ears: ClothingHeadsetGrey
    gloves: ClothingHandsGlovesFingerless
  inhand:
    - WeaponMeleeToolboxRobust

#Brigmedic

- type: startingGear
  id: BrigmedicGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitBrigmedic
    outerClothing: ClothingOuterCoatAMG
    back: ClothingBackpackBrigmedic
    shoes: ClothingShoesColorRed
    gloves: ClothingHandsGlovesNitrile
    eyes: ClothingEyesHudMedical
    head: ClothingHeadHatBeretBrigmedic
    id: BrigmedicPDA
    ears: ClothingHeadsetBrigmedic
    mask: ClothingMaskBreathMedicalSecurity
    belt: ClothingBeltMedicalFilled

# Aghost
- type: startingGear
  id: MobAghostGear
  equipment:
    back: ClothingBackpackSatchelHolding
    id: AdminPDA
  storage:
    back:
    - GasAnalyzer
    - trayScanner

#Gladiator with spear
- type: startingGear
  id: GladiatorGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitGladiator
    back: SpearBone
    head: ClothingHeadHatGladiator
    shoes: ClothingShoesCult

#Ash Walker
- type: startingGear
  id: AshWalker
  equipment:
    jumpsuit: ClothingUniformJumpsuitGladiator
    outerClothing: ClothingOuterArmorBone
    back: SpearBone
    head: ClothingHeadHelmetBone
    shoes: ClothingShoesCult

#Banana Clown
- type: startingGear
  id: BananaClown
  equipment:
    shoes: ClothingShoesClownBanana
    jumpsuit: ClothingUniformJumpsuitClownBanana
    mask: ClothingMaskClownBanana

# Limited Gear
- type: startingGear
  id: LimitedPassengerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorGrey
    shoes: ClothingShoesColorBlack

- type: startingGear
  id: LimitedSalvageSpecialistGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSalvageSpecialist
    shoes: ClothingShoesBootsSalvage

- type: startingGear
  id: LimitedPirateGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitPirate
    head: ClothingHeadBandBlack
    shoes: ClothingShoesBootsLaceup
    belt: ClothingBeltUtility