- type: antag
  id: Traitor
  name: roles-antag-syndicate-agent-name
  antagonist: true
  setPreference: true
  objective: roles-antag-syndicate-agent-objective

- type: antag
  id: BloodBrother
  name: roles-antag-bloodbrother-name
  antagonist: true
  setPreference: true
  objective: roles-antag-syndicate-bloodbrother-objective
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 3600 # 1h
